import { Animal } from './types';

export const INVENTORY: Animal[] = [
  {
    id: '1',
    name: 'Nordestino GT',
    breed: 'Pêga',
    size: 'Médio',
    year: 2023,
    price: 12500,
    hours: 450,
    temperament: 'Sport',
    traction: '4x4 (Quatro Patas)',
    fuel: 'Capim & Água',
    emissions: 'Orgânica (Zero Carbono)',
    image: '/BurroD.jpg',
    description: 'Um jegue de alta performance projetado para os terrenos mais difíceis do sertão. Confiável, robusto e pronto para o trabalho.'
  },
  {
    id: '2',
    name: 'Jegue de Luxo Platinum',
    breed: 'Gargano Italiano',
    size: 'Grande',
    year: 2024,
    price: 45000,
    hours: 50,
    temperament: 'Automático',
    traction: '4x4 (Quatro Patas)',
    fuel: 'Feno Premium & Água',
    emissions: 'Orgânica (Eco-friendly)',
    image: '/BurroB.jpg',
    isFeatured: true,
    description: 'O auge da tração de luxo. Acompanha sela de couro, ferraduras de liga leve e um temperamento calmo para os proprietários mais exigentes.'
  },
  {
    id: '3',
    name: 'Sertão Explorer',
    breed: 'Nordestino',
    size: 'Compacto',
    year: 2022,
    price: 8900,
    hours: 1200,
    temperament: 'Off-road',
    traction: '4x4 (Quatro Patas)',
    fuel: 'Capim & Água',
    emissions: 'Orgânica',
    image: '/burroA.jpg',
    description: 'Perfeito para trilhas apertadas e caminhos rochosos. Alta eficiência de combustível e baixos custos de manutenção.'
  },
  {
    id: '4',
    name: 'Burro de Carga Caatinga',
    breed: 'Mestiço',
    size: 'Pesado',
    year: 2021,
    price: 1500,
    hours: 2500,
    temperament: 'Manual',
    traction: '4x4 (Quatro Patas)',
    fuel: 'Capim & Água',
    emissions: 'Orgânica',
    image: '/burro-caido.jpg',
    description: 'Unidade com alto tempo de uso. Preço promocional para queima de estoque. Necessita de revisão no sistema de suspensão.'
  },
  {
    id: '5',
    name: 'Agreste Cruiser',
    breed: 'Pêga',
    size: 'Médio',
    year: 2024,
    price: 18500,
    hours: 120,
    temperament: 'Sport',
    traction: '4x4 (Quatro Patas)',
    fuel: 'Capim & Água',
    emissions: 'Orgânica',
    image: '/BurroE.jpg',
    description: 'Uma condução suave com excelente dirigibilidade. Ideal para viagens de longa distância entre fazendas.'
  },
  {
    id: '6',
    name: 'Edição Vaquejada',
    breed: 'Quarto de Milha Mix',
    size: 'Grande',
    year: 2023,
    price: 28000,
    hours: 800,
    temperament: 'Sport',
    traction: '4x4 (Quatro Patas)',
    fuel: 'Capim Premium',
    emissions: 'Orgânica',
    image: '/BurroC.jpg',
    description: 'Edição especial para eventos de vaquejada. Alta aceleração e curvas rápidas.'
  }
];
